"""Add date_updated to comment

Revision ID: 0bbce901f1c2
Revises: 0de5ed829591
Create Date: 2024-04-30 09:38:24.410020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbce901f1c2'
down_revision: Union[str, None] = '0de5ed829591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('date_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'date_updated')
    # ### end Alembic commands ###
