"""fix delete orphan tags end

Revision ID: 406b5f0a5a77
Revises: b9c885590cc1
Create Date: 2024-05-06 00:12:07.297795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406b5f0a5a77'
down_revision: Union[str, None] = 'b9c885590cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
