"""Delete user_id from comment

Revision ID: 47585adda035
Revises: 0bbce901f1c2
Create Date: 2024-04-30 11:23:57.999077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47585adda035'
down_revision: Union[str, None] = '0bbce901f1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_user_id_fkey', 'tags', type_='foreignkey')
    op.drop_column('tags', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tags_user_id_fkey', 'tags', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
