"""Add description field to photo

Revision ID: ddb40fcfe149
Revises: beb8b046da1a
Create Date: 2024-04-25 08:26:53.259961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb40fcfe149'
down_revision: Union[str, None] = 'beb8b046da1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('description', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'description')
    # ### end Alembic commands ###
